# Generated by Django 5.1.6 on 2025-03-04 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
