# Generated by Django 5.1.6 on 2025-03-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='addons',
            field=models.ManyToManyField(blank=True, related_name='addon_for', to='products.product'),
        ),
    ]
